# [START runtime]
runtime: python
env: flex
threadsafe: yes
entrypoint: gunicorn -b :$PORT daesun.wsgi

beta_settings:
    cloud_sql_instances: daesun2017:asia-east1:mysql

runtime_config:
  python_version: 3
# [END runtime]

env_variables:
  MEMCACHE_SERVER: 104.199.215.251:11211

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 20
  cool_down_period_sec: 120 # default value
  cpu_utilization:
    target_utilization: 0.8