# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_pledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pledge',
            name='unlike',
            field=models.IntegerField(default=0),
        ),
    ]
